// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PharmacyBlockRequest pharmacy block request
//
// swagger:model PharmacyBlockRequest
type PharmacyBlockRequest struct {

	// pharmacy name
	PharmacyName string `json:"pharmacy_name"`
}

// Validate validates this pharmacy block request
func (m *PharmacyBlockRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this pharmacy block request based on context it is used
func (m *PharmacyBlockRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PharmacyBlockRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PharmacyBlockRequest) UnmarshalBinary(b []byte) error {
	var res PharmacyBlockRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
