// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PurchaseConfirmRequest purchase confirm request
//
// swagger:model PurchaseConfirmRequest
type PurchaseConfirmRequest struct {

	// is social card
	IsSocialCard bool `json:"is_social_card,omitempty"`

	// purchase uuid
	// Format: uuid
	PurchaseUUID strfmt.UUID `json:"purchase_uuid,omitempty"`
}

// Validate validates this purchase confirm request
func (m *PurchaseConfirmRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validatePurchaseUUID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PurchaseConfirmRequest) validatePurchaseUUID(formats strfmt.Registry) error {
	if swag.IsZero(m.PurchaseUUID) { // not required
		return nil
	}

	if err := validate.FormatOf("purchase_uuid", "body", "uuid", m.PurchaseUUID.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this purchase confirm request based on context it is used
func (m *PurchaseConfirmRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PurchaseConfirmRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PurchaseConfirmRequest) UnmarshalBinary(b []byte) error {
	var res PurchaseConfirmRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
