// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PurchaseAddRequest purchase add request
//
// swagger:model PurchaseAddRequest
type PurchaseAddRequest struct {

	// position
	Position string `json:"position,omitempty"`

	// product name
	ProductName string `json:"product_name,omitempty"`

	// purchase uuid
	PurchaseUUID string `json:"purchase_uuid,omitempty"`
}

// Validate validates this purchase add request
func (m *PurchaseAddRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this purchase add request based on context it is used
func (m *PurchaseAddRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PurchaseAddRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PurchaseAddRequest) UnmarshalBinary(b []byte) error {
	var res PurchaseAddRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
