// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// UserBlockRequest user block request
//
// swagger:model UserBlockRequest
type UserBlockRequest struct {

	// email
	Email string `json:"email"`
}

// Validate validates this user block request
func (m *UserBlockRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this user block request based on context it is used
func (m *UserBlockRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *UserBlockRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UserBlockRequest) UnmarshalBinary(b []byte) error {
	var res UserBlockRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
